version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:3.7.4
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=${NORDVPN_USERNAME}
      - PASS=${NORDVPN_PASSWORD}
      - CONNECT=${NORDVPN_CONNECTION}
      - TECHNOLOGY=OpenVPN
      - NETWORK=${HOST_SUBNET}
    ports:
      # Transmission
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 49153:49153
      - 49153:49153/udp
        # Jackett
      - 9117:9117
        # RADAR
      - 7878:7878
        # OMBI
      - 3579:3579
        # SONARR
      - 8989:8989
        # LIDARR
      - 8686:8686
        # Lazylibrarian
      - 5299:5299
      - 8112:8112
        # Bazarr
      - 6767:6767
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: bridge
  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #  - UMASK_SET=<022> #optional
    volumes:
      - ${CONFIG_DIRECTORY}emby/config:/config
      - ${DATA_DIRECTORY}Shows:/data/tvshows
      - ${DATA_DIRECTORY}Movies:/data/movies
      - ${DATA_DIRECTORY}music:/data/music
      - ${DATA_DIRECTORY}books:/data/books
    #  - /path/for/transcoding:/transcode #optional
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
    #  - /dev/dri:/dev/dri #optional
      - /dev/vchiq:/dev/vchiq #optional
    #  - /dev/video10:/dev/video10 #optional
    #  - /dev/video11:/dev/video11 #optional
    #  - /dev/video12:/dev/video12 #optional
    restart: always
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONFIG_DIRECTORY}deluge/config:/config
        #- ${DATA_DIRECTORY}torrents:/downloads
      - ${DATA_DIRECTORY}torrents:/mnt/media/torrents
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIRECTORY}jackett/config:/config
      - ${DATA_DIRECTORY}torrents/completed:/downloads
    depends_on:
      - vpn
    restart: always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIRECTORY}sonarr/config:/config
      - ${DATA_DIRECTORY}:/mnt/media
    restart: always
    depends_on:
      - vpn
      - deluge
      - jackett
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIRECTORY}radarr/config:/config
      - ${DATA_DIRECTORY}:/mnt/media
    restart: always
    depends_on:
      - vpn
      - deluge
      - jackett
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - vpn
      - deluge
      - jackett
    volumes:
      - ${CONFIG_DIRECTORY}lidarr/config:/config
      - ${DATA_DIRECTORY}music:/music
      - ${DATA_DIRECTORY}torrents/complete:/mnt/media/torrents/complete
    restart: always
#  heimdall:
#    image: linuxserver/heimdall
#    container_name: heimdall
#    restart: always
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    ports:
#      - 20080:80
#      - 20443:443
#    volumes:
#      - ./heimdall/config:/config
#  ddclient:
#    image: ghcr.io/linuxserver/ddclient
#    container_name: ddclient
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ./ddclient/config:/config
#    restart: unless-stopped
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
      - LANG=en_US
    volumes:
      - ${CONFIG_DIRECTORY}lazylibrarian/config:/config
      - ${DATA_DIRECTORY}torrents/complete:/downloads
      - ${DATA_DIRECTORY}books:/books
      - ${DATA_DIRECTORY}audioBooks:/audioBooks
    network_mode: service:vpn
    #ports:
    #  - 5299:5299
    restart: always
    depends_on:
      - vpn
      - deluge
      - jackett
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIRECTORY}bazarr/config:/config
      - ${DATA_DIRECTORY}Shows:/tv
      - ${DATA_DIRECTORY}Movies:/movies
    network_mode: service:vpn
    restart: always
    depends_on:
      - vpn
