version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # node port. It should be mapped on this container because
                  # the node container use the network from the main container
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - ${CONFIG_DIRECTORY}tdarr/server:/app/server
      - ${CONFIG_DIRECTORY}tdarr/configs:/app/configs
      - ${CONFIG_DIRECTORY}tdarr/logs:/app/logs
      - ${DATA_DIRECTORY}:/media

  tdarr-node:
    container_name: tdarr-node
    image: haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeID=MainNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - serverIP=0.0.0.0
      - serverPort=8266
    volumes:
      - ${CONFIG_DIRECTORY}tdarr/configs:/app/configs
      - ${CONFIG_DIRECTORY}tdarr/logs:/app/logs
      - ${DATA_DIRECTORY}:/media
